### PR TITLE
Add otp-25 support

### PR DESCRIPTION
**Pull request by zyuyou**
1. Add otp-25 `maybe_expr` support. #970 
2. Fix "Setup SDK" suggests. #977 
3. Fix rebar version check. #903

### CODE REVIEW

**Comment by kvakvs** [comment]
Code looks good
Also fixes one bug which i tried to fix myself, in an experimental branch (Setup SDK button
I'll give it a try soon

**Comment by kvakvs** [comment]
I rebased this on latest master (dropped the last commit, due to conflicts) and trying to build ZIP archive for testing it shows 4 failed tests. I will spend more time checking whether i did rebase wrong, or how to fix those tests.

**Comment by zyuyou** [comment]
@kvakvs it's ok now

**Comment by kvakvs** [comment]
Reviewed it twice and running it now, too. Great job, thank you. Will merge soon.

**Pull request merged**
