### PR TITLE
Add duplicate behaviour inspection

### PR DESCRIPTION
**Pull request by telezhnaya**

### CODE REVIEW

**Comment by telezhnaya** [comment]
I feel you meant more, but I don't know how to clean it up better than now. Help me please.

**Comment by telezhnaya** [comment]
I have removed PSI elements from fix. Check it please.

**Comment by deadok22** [comment]
It's good. But you'll have to add highlighting tests for your inspection.

**Comment by telezhnaya** [comment]
Done.

**Comment by telezhnaya** [comment]
Renamed all tests. Check it please.

**Comment by telezhnaya** [comment]
Check it please.

**Comment by telezhnaya** [comment]
Check it please.

**Comment by telezhnaya** [comment]
Check it please.

**Pull request merged**
