### PR TITLE
Add -optional_callbacks() attribute

### PR DESCRIPTION
**Pull request by telezhnaya**

### CODE REVIEW

**Comment by deadok22** [comment]
First of all, whenever you alter the grammar, add tests for your changes.

Second, your newly added rule has the same structure as export_functions has, but lacks a pin attribute - it will make parsing fail when there's no closing bracket, for example.

Third, you'll have to highlight 'optional_callbacks' as an attribute.

Fourth,  it doesn't really make sense to add new PSI elements without using them - add at least one use case for the new PSI in a separate commit.

**Comment by telezhnaya** [comment]
Test was added in my first pull request.
https://github.com/telezhnaya/intellij-erlang/commit/7d4e524ec7bd14fa87abd58afdc001867dfed4cb#diff-8d95db0050dfa52a0bbbc73577e900f0R184
I haven't found no more tests for such changes.
Other mistakes have corrected.

I am planning to add Erlang18SyntaxInspection and fix org.intellij.erlang.inspection.ErlangUndefinedCallbackFunctionInspection. 
So, it would be great if you check this pull request and leave it opened. I am going to make this two inspections in other pull requests. When they would be fine you could merge them all.

**Comment by telezhnaya** [comment]
Or it would be better to make inspections in other commits in same branch. What do you think?

**Comment by deadok22** [comment]
Tests you're talking about are completion tests, whereas you changed our grammar, which changed our parser. So you have to add parser tests as well. You also should test parser's recovery when optional_callback attribute is incomplete.

I'd still want you to add at least one usage for your new PSI, so it would be great to have your inspections in this pull request.

**Comment by telezhnaya** [comment]
Check it please.

**Comment by deadok22** [comment]
Your inspection marks code red, while it compiles just fine on releases prior to 18. It makes sense to lower your error message severity.

**Comment by telezhnaya** [comment]
Check it please.

**Pull request merged**
