### PR TITLE
#622: Illegal guard inspection

### PR DESCRIPTION
**Pull request by telezhnaya**

### CODE REVIEW

**Comment by deadok22** [comment]
Make sure you inspect all constructions where guards are available.

**Comment by deadok22** [comment]
I asked you to inspect all constructions where guards are available. It's still not done.

**Comment by telezhnaya** [comment]
Check it please.

**Comment by telezhnaya** [comment]
Check it please.
I have fixed problem with guards in another constructions.

**Comment by telezhnaya** [comment]
Added more tests.

**Pull request merged**
