### PR TITLE
Fixed erlang doc reader

### PR DESCRIPTION
**Pull request by zsoci**
As erlang.org has the docs for major.minor version only, it is needed to cut the fixes as being the third part of the version string in order to use the last major.minor docs online.
In addition when html docs are generated locally with kerl, the correct directory shall be set for finding the docs locally.

### CODE REVIEW

**Comment by ignatov** [comment]
@zsoci Hi, why you decided to delete the PR?

**Comment by zsoci** [comment]
I saw a lot of files changed and I did not want to open a PR with a lot of garbage in it. I am not familiar with gradle and the stuff needed for intellij plugins, did not want to take your time to coach a newbie in this field. I see a lot of diff to master that I have no idea if those are correct.

Anyway I forked again and made a PR on that fork for you to take a look at the diff in case you are interested. If you think I should make a PR on your project, let me know. Also I will appreciate if you will let me know what is needed for the real PR.

**Comment by ignatov** [comment]
Oh, please do a new PR.

**Comment by zsoci** [comment]
Done https://github.com/ignatov/intellij-erlang/pull/872

**Pull request closed without merging**
