### PR TITLE
#923 URL<->Path conversions are done without invoking VirtualFileManager

### PR DESCRIPTION
**Pull request by piosok**

### CODE REVIEW

**Comment by ignatov** [comment]
Thanks for the PR, could you please elaborate a bit on why you decided to change that behavior?

**Comment by piosok** [comment]
As described in https://github.com/ignatov/intellij-erlang/issues/923, 
the output of erlc is not parsed/displayed correctly (actually not at all).

**Review by kvakvs — COMMENTED** [review]
Looks nice

**Comment by ignatov** [comment]
Thanks an sorry for the long response.

**Pull request merged**
